language: node_js

node_js:
  - "5.5"
  - "4.2"

install:
  - npm i sidekick

script:
  - sidekick -v
  - sidekick run --ci

notifications:
  email: false
  slack: we-are-sidekick:GeIT5wtuKMLImpFXYHWzIGzI
